global:
  BTN_SIDE:
    type: keyboard
    payload: alt+left
  BTN_EXTRA:
    type: keyboard
    payload: alt+right

global_gestures:
  UP:
    type: command
    payload: swaymsg workspace next
  DOWN:
    type: command
    payload: swaymsg workspace prev

profiles:
  - app_name: firefox
    mappings:
      BTN_SIDE:
        type: keyboard
        payload: alt+left
      BTN_EXTRA:
        type: keyboard
        payload: alt+right
      REL_HWHEEL:
        type: command
        payload: swaymsg workspace next
    gestures:
      LEFT:
        type: keyboard
        payload: alt+left
      RIGHT:
        type: keyboard
        payload: alt+right

  - app_name: vscode
    mappings:
      BTN_SIDE:
        type: keyboard
        payload: ctrl+shift+p
      BTN_EXTRA:
        type: keyboard
        payload: ctrl+p
    gestures:
      UP:
        type: keyboard
        payload: ctrl+shift+n
      DOWN:
        type: keyboard
        payload: ctrl+shift+t
